---
name: CI

on:
  workflow_call: # Allow this config to be reused by other workflows in the repo
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          cache: poetry
      - run: |
          # Run pre-commit against all files
          poetry install
          poetry run pre-commit run -a

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          cache: poetry
      - run: |
          # Run pytest and generate coverage report
          poetry install
          poetry run pytest --cov file_store --cov-report xml -v
      - uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: coverage.xml
